### ISSUE TITLE
Cannot find module 'menubar'

### ISSUE THREAD

**Issue by basiclaser** [maxogden/menubar#175]
Hi, struggling to run an OSX build of my menubar electron app. 
the app runs fine when i run `./node_modules/electron/dist/Electron.app/Contents/MacOS/Electron .`
but after building with `electron-packager . projectname --icon "assets/1024.icns" --overwrite`
I can't run the application. I get the following error: 
<img width="459" alt="screen shot 2017-05-27 at 16 07 06" src="https://cloud.githubusercontent.com/assets/3663537/26520131/d14ea702-42f6-11e7-8c59-f548d0de5785.png">

I checked my package.json dependencies and they seem fine: 
```
  "dependencies": {
    "electron": "~1.6.2",
    "menubar": "^5.2.3"
  }
``

**Comment by eddiezane** [comment]
I encountered the same error and saw that the `menubar` folder is not included in the `node_modules` folder generated by `electron-packager` at `my.app/Contents/Resources/app/node_modules`.

Running `electron-packager` with the `--no-prune` option from the docs fixed this.

It seems that pruning is on by default since https://github.com/electron-userland/electron-packager/pull/472

**Comment by amaurymartiny** [comment]
Closing, please re-open if Eddie's solution didn't work.
